version: '3.8' # VersAo do Docker Compose

services:
  banco-chu-api:
    image: banco-chu-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Porta do host -> Porta no container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    networks:
      - bancochuapi_banco-chu-network # Rede personalizada

networks:
  bancochuapi_banco-chu-network:
    driver: bridge # Define o driver da rede
