version: '3.8'

services:
  banco-chu-api:
    image: banco-chu-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  
      - "5001:443" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # Mudar para "Production"
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    networks:
      - bancochuapi_banco-chu-network

networks:
  bancochuapi_banco-chu-network:
    driver: bridge
